const PRESETS = {
    they: {
        name: "They/Them",
        subjective: "they",
        objective: "them",
        possessiveDeterminer: "their",
        possessive: "theirs",
        reflexive: "themself",
        singularVerbs: false,
    },
    xe: {
        name: "Xe/Xem",
        subjective: "xe",
        objective: "xem",
        possessiveDeterminer: "xyr",
        possessive: "xyrs",
        reflexive: "xemself",
        singularVerbs: true,
    },
    it: {
        name: "It/Its",
        subjective: "it",
        objective: "it",
        possessiveDeterminer: "its",
        possessive: "its",
        reflexive: "itself",
        singularVerbs: true,
    },
    she: {
        name: "She/Her",
        subjective: "she",
        objective: "her",
        possessiveDeterminer: "her",
        possessive: "hers",
        reflexive: "herself",
        singularVerbs: true,
    },
    he: {
        name: "He/Him",
        subjective: "he",
        objective: "him",
        possessiveDeterminer: "his",
        possessive: "his",
        reflexive: "himself",
        singularVerbs: true,
    },
}

const PROMPTS = [
    "{subjective} {is/are} a great friend.",
    "{subjective} {loves/love} cats.",
    "That belongs to {objective}.",
    "I already asked {objective} that.",
    "That's {possessiveDeterminer} pencil.",
    "I love {possessiveDeterminer} hair.",
    "{possessiveDeterminer} room is upstairs.",
    "That book is {possessive}.",
    "I am friends of {possessive}.",
    "{subjective} made {reflexive} a sandwich.",
    "{subjective} drew that all by {reflexive}.",
]