const PRESETS = {
    ae: {
        name: "Ae/Aer",
        subjective: "ae",
        objective: "aer",
        possessiveDeterminer: "aer",
        possessive: "aers",
        reflexive: "aerself",
        singularVerbs: true,
        categories: ["misc"],
    },
    ey: {
        name: "Ey/Em",
        subjective: "ey",
        objective: "em",
        possessiveDeterminer: "eir",
        possessive: "eirs",
        reflexive: "emself",
        singularVerbs: true,
        categories: ["misc"],
    },
    fae: {
        name: "Fae/Faer",
        subjective: "fae",
        objective: "faer",
        possessiveDeterminer: "faer",
        possessive: "faers",
        reflexive: "faerself",
        singularVerbs: true,
        categories: ["mythical"],
    },
    he: {
        name: "He/Him",
        subjective: "he",
        objective: "him",
        possessiveDeterminer: "his",
        possessive: "his",
        reflexive: "himself",
        singularVerbs: true,
        categories: ["traditional"],
    },
    it: {
        name: "It/Its",
        subjective: "it",
        objective: "it",
        possessiveDeterminer: "its",
        possessive: "its",
        reflexive: "itself",
        singularVerbs: true,
        categories: ["gender neutral"],
    },
    she: {
        name: "She/Her",
        subjective: "she",
        objective: "her",
        possessiveDeterminer: "her",
        possessive: "hers",
        reflexive: "herself",
        singularVerbs: true,
        categories: ["traditional"],
    },
    they: {
        name: "They/Them",
        subjective: "they",
        objective: "them",
        possessiveDeterminer: "their",
        possessive: "theirs",
        reflexive: "themself",
        singularVerbs: false,
        categories: ["traditional", "gender neutral"],
    },
    thon: {
        name: "Thon/Thons",
        subjective: "thon",
        objective: "thon",
        possessiveDeterminer: "thons",
        possessive: "thons",
        reflexive: "thonself",
        singularVerbs: true,
        categories: ["gender neutral"],
    },
    xe: {
        name: "Xe/Xem",
        subjective: "xe",
        objective: "xem",
        possessiveDeterminer: "xyr",
        possessive: "xyrs",
        reflexive: "xemself",
        singularVerbs: true,
        categories: ["gender neutral"],
    },
}
 
const PROMPTS = [
    "{subjective} {is/are} a great friend.",
    "{subjective} {loves/love} cats.",
    "I think {subjective} {is/are} awesome.",
    "{subjective} {has/have} cool hair.",
    
    "That belongs to {objective}.",
    "I already asked {objective} that.",
    "I saw {objective} with {possessiveDeterminer} best friend.",
    "{subjective} put {possessiveDeterminer} backpack on.",

    "That's {possessiveDeterminer} pencil.",
    "I love {possessiveDeterminer} hair.",
    "{possessiveDeterminer} room is upstairs.",
    "{possessiveDeterminer} shirt is awesome.",
    "A smile lit up {possessiveDeterminer} face.",
    "I love {possessiveDeterminer} cooking.",

    "That book is {possessive}.",
    "I like your shoes but {possessive} are amazing.",
    "I found my seat but {subjective} {was/were} still looking for {possessive}.",

    "{subjective} made {reflexive} a sandwich.",
    "{subjective} drew that all by {reflexive}.",
    "{subjective} bought {reflexive} a car.",
    "{subjective} sat all by {reflexive}."
]